site_name: Generative AI Use Cases (GenU)
site_url: https://aws-samples.github.io/generative-ai-use-cases/

repo_url: https://github.com/aws-samples/generative-ai-use-cases
repo_name: aws-samples/generative-ai-use-cases
edit_uri: blob/main/docs

watch: [mkdocs.yml, README.md, browser-extension/README.md]
use_directory_urls: false

copyright: © 2025, Amazon Web Services, Inc. or its affiliates. All rights reserved.

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.trackings
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    media: '(prefers-color-scheme: light)'
    scheme: default
    primary: custom
    accent: deep-orange
  font:
    text: Roboto
    code: Roboto Mono
  language: en
extra_css:
  - assets/stylesheets/custom/custom.css

nav:
  - Overview: index.md
  - Getting started:
      - Deploy:
          - Quick Start: ABOUT.md
          - (Optional) Deploy with AWS CloudShell: DEPLOY_ON_CLOUDSHELL.md
          - Deploy Options: DEPLOY_OPTION.md
      - Authentication:
          - Authenticate with Google Workspace: SAML_WITH_GOOGLE_WORKSPACE.md
          - Authenticate with Microsoft Entra ID: SAML_WITH_ENTRA_ID.md
      - Browser Extension:
          - Overview: EXTENSION.md
          - Build: EXTENSION_BUILD.md
          - Install: EXTENSION_INSTALL.md
          - SAML Authentication: EXTENSION_SAML.md
      - Other:
          - Update: UPDATE.md
          - Local Development Environment: DEVELOPMENT.md
          - Delete Resources: DESTROY.md
          - Use as a Native App: PWA.md

extra:
  # Used in custom hook anchors.py
  absolute_path_replace_uri: https://github.com/aws-samples/generative-ai-use-cases/blob/main/
  replace_dict:
    '../../README.md': '../en/ABOUT.html'
    '../../README_ja.md': '../ja/ABOUT.html'
    '../../README.md#deployment': '../en/ABOUT.html#deployment'
    '../../README_ja.md#デプロイ': '../ja/ABOUT.html#デプロイ'

plugins:
  - include-markdown:
      rewrite_relative_urls: true
  - gh-admonitions
  - search
  - social
  - i18n:
      docs_structure: folder
      force_default_in_subdirectory: true
      reconfigure_search: true
      languages:
        - locale: en
          name: English
          default: true
        - locale: ja
          name: 日本語
          nav_translations:
            Overview: 概要
            Deploy: デプロイ方法
            Quick Start: クイックスタート
            (Optional) Deploy with AWS CloudShell: (オプション) AWS CloudShell でデプロイする
            Deploy Options: デプロイオプション
            Authentication: 認証
            Authenticate with Google Workspace: Google Workspace で認証する
            Authenticate with Microsoft Entra ID: Microsoft Entra ID で認証する
            Browser Extension: ブラウザ拡張機能
            Build: ビルド
            Install: インストール
            SAML Authentication: SAML 認証
            Other: その他
            Update: アップデート方法
            Local Development Environment: ローカル開発環境構築手順
            Delete Resources: リソースの削除方法
            Use as a Native App: ネイティブアプリのように利用する方法
hooks:
  - docs/overrides/hooks/anchors.py

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

validation:
  links:
    absolute_links: info
    anchors: warn
    unrecognized_links: warn
