site_name: Generative AI Use Cases JP (GenU)
site_url: https://aws-samples.github.io/generative-ai-use-cases-jp/
site_description: すぐに業務活用できるビジネスユースケース集付きの安全な生成AIアプリ実装

repo_url: https://github.com/aws-samples/generative-ai-use-cases-jp
repo_name: aws-samples/generative-ai-use-cases-jp
edit_uri: blob/main/docs

watch: [mkdocs.yml, README.md, browser-extension/README.md]
use_directory_urls: false

copyright: © 2025, Amazon Web Services, Inc. or its affiliates. All rights reserved.

theme:
  name: material
  custom_dir: docs/mkdocs/material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.trackings
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    media: '(prefers-color-scheme: light)'
    scheme: default
    primary: custom
    accent: deep-orange
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/favicon.svg
  # logo: assets/favicon.svg
  language: ja
extra_css:
  - assets/stylesheets/custom/custom.css

nav:
  - 概要: index.md
  - Getting started:
      - デプロイ方法:
          - クイックスタート: ABOUT.md
          - (オプション) AWS CloudShell でデプロイする: DEPLOY_ON_CLOUDSHELL.md
          - デプロイオプション: DEPLOY_OPTION.md
      - 認証:
          - Google Workspace で認証する: SAML_WITH_GOOGLE_WORKSPACE.md
          - Microsoft Entra ID で認証する: SAML_WITH_ENTRA_ID.md
      - ブラウザ拡張機能:
          - 概要: EXTENSION.md
          - ビルド: EXTENSION_BUILD.md
          - インストール: EXTENSION_INSTALL.md
          - SAML 認証: EXTENSION_SAML.md
      - その他:
          - アップデート方法: UPDATE.md
          - ローカル開発環境構築手順: DEVELOPMENT.md
          - リソースの削除方法: DESTROY.md
          - ネイティブアプリのように利用する方法: PWA.md

extra:
  # Used in custom hook anchors.py
  absolute_path_replace_uri: https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/

plugins:
  - include-markdown:
      rewrite_relative_urls: true
  - gh-admonitions
  - search
  - social

hooks:
  - docs/mkdocs/material/overrides/hooks/anchors.py

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

validation:
  links:
    absolute_links: info
    anchors: warn
    unrecognized_links: warn
